@startuml personal-loan
title Sequence Diagram for the personal loan flow

BAP -> BG: /search
activate BAP
activate BG
deactivate BAP
deactivate BG

BG -> BPP: /search
activate BG
activate BPP
deactivate BG


BPP -> BPPService: type of loan
activate BPPService

BPPService -> BPP: get services
deactivate BPPService


BPP -> BG: /on_search
activate BG
deactivate BPP
deactivate BG

BG -> BAP: /on_search
activate BAP
activate BG
deactivate BAP
deactivate BG

BAP -> BPP: /select
activate BAP
activate BPP
deactivate BAP

BPP -> BPPService: chosen lender, offer
activate BPPService

BPPService -> BPP: get quotes
deactivate BPPService

BPP -> BAP: /on_select
activate BAP
deactivate BPP
deactivate BAP

BAP -> BPP: /init
activate BAP
activate BPP
deactivate BAP

BPP -> BPPService: personal details
activate BPPService

BPPService -> BPP: get offer details
deactivate BPPService

BPP -> BAP: /on_init
activate BAP
deactivate BPP
deactivate BAP

BAP -> BPP: /confirm
activate BAP
activate BPP
deactivate BAP

BPP -> BPPService: confirmed loan application
activate BPPService

BPPService -> BPP: get confirmation details
deactivate BPPService

BPP -> BAP: /on_confirm
activate BAP
deactivate BPP
deactivate BAP

@enduml